
["Adventurer Zombie Equipment"]
	#Items / chance of spawning with it
	"Head Slot" = ["minecraft:chainmail_helmet|50", "minecraft:iron_helmet|20", "minecraft:golden_helmet|20"]
	"Chest Slot" = ["minecraft:chainmail_chestplate|50", "minecraft:iron_chestplate|20", "minecraft:golden_chestplate|20"]
	"Main Hand Slot" = ["minecraft:stone_sword|50", "minecraft:golden_sword|20", "minecraft:iron_axe|25", "minecraft:golden_axe|20", "minecraft:iron_sword|30"]

