
["Critter Spawning"]
	"Elk Spawning" = true
	"Coyote Spawning" = true
	"Greywolf Spawning" = true
	"Whitetail Spawning" = true
	"Cougar Spawning" = true
	"Wolverine Spawning" = true
	"Ringtail Spawning" = true
	"Giant Boar Spawning" = true
	"Goose Spawning" = true
	"Black Bear Spawning" = true
	"Beaver Spawning" = true
	"Mouse Spawning" = true
	"Snake Spawning" = true
	"Rattlesnake Spawning" = true
	"Pit Viper Spawning" = true

["Crawler Spawning"]
	"Wendigo Spawning" = true
	"Bewitched Greywolf Spawning" = true
	"Chupacabra Spawning" = true
	"Squonk Spawning" = true
	"Howler Spawning" = true
	"Sasquatch Spawning" = true
	"Wechuge Spawning" = true

[Other]
	#How long an Effigy lasts when lighten up. This is measured in seconds.
	"Effigy Light" = 3000.0

